version: '3.7'

services:
    java-service:
        build:
            context: .
            dockerfile: ${DOCKERFILE_JAVA_SERVICE}
        image: ${IMAGE_NAME}-service
        container_name: ${IMAGE_NAME}
        ports:
            - 8080:8080
        environment:
            - CONTEXT_PATH=${CONTEXT_PATH}
            - SPRING_PROFILE=${SPRING_PROFILE}

            # switch between POSTGRES_HOST_LOCALHOST and POSTGRES_HOST_CONTAINER
            - POSTGRES_HOST=${POSTGRES_HOST_CONTAINER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            - postgres

        networks:
            - axa-network
    
    postgres:
        image: ${POSTGRES_IMAGE}
        container_name: ${CONTAINER_PREFIX}-postgres
        ports:
            - '5432:5432'
        volumes:
            - ${POSTGRES_MASTER_DATA}:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=POSTGRES_DB
            - POSTGRES_PASSWORD=password
        networks:
            - axa-network
        
networks:
    axa-network:
        name: axa-network