server:
    port: 8080

spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
